[context."feature/ci-cd".environment]
  VUE_APP_ATLAS_GRAPHQL_ENDPOINT = "https://sv-mini-atlas.herokuapp.com/graphql/"
[context."tokens-demo".environment]
  VUE_APP_ATLAS_GRAPHQL_ENDPOINT = "https://mini-stack-a-spike-toke-t7jtur.herokuapp.com/graphql/"
